- name: Systemd | Reload daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: QoS | Restart qos-follow service
  ansible.builtin.systemd:
    name: qos-follow.service
    state: restarted
  failed_when: false

- name: QoS | Restart vff-qos-nft service
  ansible.builtin.systemd:
    name: "{{ qos_nft_unit_name }}.service"
    state: restarted
  failed_when: false
