---
galaxy_info:
  role_name: qos_per_user_xray
  author: Sergey Ryabkov
  description: Per-user traffic shaping (QoS) for Xray nodes using conntrack marks, nftables and tc/ifb (HTB).
  license: MIT
  min_ansible_version: "2.17"

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

dependencies: []
